---
version: 2.0
jobs:
  php55:
    docker:
      - image: googleapis/php:5.5
    steps:
      - checkout
      - run:
          name: Install PHP library
          command: composer install
      - run:
          name: Run GAPIC unit tests in PHP 5.5
          command: ./vendor/bin/phpunit
      - run:
          name: Run phpcs format check in PHP 5.5
          command: ./vendor/bin/phpcs --standard=./generated/php/phpcs-ruleset.xml
    working_directory: /var/code/googleapis/

  php56:
    docker:
      - image: googleapis/php:5
    steps:
      - checkout
      - run:
          name: Install PHP library
          command: composer install
      - run:
          name: Run GAPIC unit tests in PHP 5.6
          command: ./vendor/bin/phpunit
      - run:
          name: Run phpcs format check in PHP 5.6
          command: ./vendor/bin/phpcs --standard=./generated/php/phpcs-ruleset.xml
    working_directory: /var/code/googleapis/

  php70:
    docker:
      - image: googleapis/php:7.0
    steps:
      - checkout
      - run:
          name: Install PHP library
          command: composer install
      - run:
          name: Run GAPIC unit tests in PHP 7.0
          command: ./vendor/bin/phpunit
      - run:
          name: Run phpcs format check in PHP 7.0
          command: ./vendor/bin/phpcs --standard=./generated/php/phpcs-ruleset.xml
    working_directory: /var/code/googleapis/

  php71:
    docker:
      - image: googleapis/php:7.1
    steps:
      - checkout
      - run:
          name: Install PHP library
          command: composer install
      - run:
          name: Run GAPIC unit tests in PHP 7.1
          command: ./vendor/bin/phpunit
      - run:
          name: Run phpcs format check in PHP 7.1
          command: ./vendor/bin/phpcs --standard=./generated/php/phpcs-ruleset.xml
    working_directory: /var/code/googleapis/

  php72:
    docker:
      - image: googleapis/php:7.2
    steps:
      - checkout
      - run:
          name: Install PHP library
          command: composer install
      - run:
          name: Run GAPIC unit tests in PHP 7.2
          command: ./vendor/bin/phpunit
      - run:
          name: Run phpcs format check in PHP 7.2
          command: ./vendor/bin/phpcs --standard=./generated/php/phpcs-ruleset.xml
    working_directory: /var/code/googleapis/

workflows:
  version: 2
  tests:
    jobs:
      - php55
      - php56
      - php70
      - php71
      - php72
      - sync_to_private:
          requires:
            - php55
            - php56
            - php70
            - php71
            - php72
          filters:
            branches:
              only: master
